  apt-get install -y \
        tofrodos \
        iproute2 \
        gawk \
        net-tools \
        libncurses5-dev \
        libncursesw5-dev \
        zlib1g:i386 \
        libssl-dev \
        flex \
        bison \
        libselinux1 \
        gnupg \
        wget \
        diffstat \
        chrpath \
        socat \
        xterm \
        autoconf \
        libtool \
        tar \
        unzip \
        texinfo \
        zlib1g-dev \
        gcc-multilib \
        build-essential \
        screen \
        pax \
        gzip \
        python2.7 \
        binutils \
        cpio \
        expect \
        file \
        fonts-noto-cjk \
        git \
        git-lfs \
        gosu \
        lib32z1-dev \
        libglib2.0-dev \
        libgtk2.0-0 \
        libsdl1.2-dev \
        libtool-bin \
        locales \
        lsb-release \
        ncurses-dev \
        sudo \
        u-boot-tools \
        vim \
        xvfb \
        bc \
        rsync \
	libncurses5 \
	x11-apps \
	iputils-ping \
	net-tools \
	openssh-server \
	csh \
	libswt-gtk-4-jni \
	dbus-x11 \
	global \
	sshpass \
	libtinfo-dev